const libraryShared={
  gu:{home:'મુખ્ય પાનું',projects:'પ્રકલ્પો',library:'જ્ઞાનાલય',pilot:'ડિજિટલ સાથી',join:'જોડાઓ',languageLabel:'ભાષા પસંદ કરો',skip:'મુખ્ય સામગ્રી પર જાઓ',footer:'અનુસૂચિત જાતિની મહિલાઓની માલિકી, નેતૃત્વ અને સંચાલન હેઠળની શિક્ષણ અને સાંસ્કૃતિક પહેલ, જે દરેકને સન્માનથી આવકારે છે.',principles:'શીખણ • સર્જનાત્મકતા • ગૌરવ • પ્રકૃતિ • સમુદાય'},
  en:{home:'Home',projects:'Projects',library:'Library',pilot:'Digital Saheli',join:'Join',languageLabel:'Choose language',skip:'Skip to main content',footer:'An education and cultural initiative owned, led and run by Scheduled Caste women, welcoming everyone with dignity.',principles:'Learning • Creativity • Dignity • Nature • Community'},
  hi:{home:'मुख्य पृष्ठ',projects:'परियोजनाएँ',library:'ज्ञानालय',pilot:'डिजिटल सहेली',join:'जुड़ें',languageLabel:'भाषा चुनें',skip:'मुख्य सामग्री पर जाएँ',footer:'अनुसूचित जाति की महिलाओं के स्वामित्व, नेतृत्व और संचालन वाली शिक्षा और सांस्कृतिक पहल, जो सभी का सम्मान के साथ स्वागत करती है।',principles:'शिक्षा • रचनात्मकता • गरिमा • प्रकृति • समुदाय'}
};
const libraryPages={
  library:{
    gu:{title:'ગુરુશાળા જ્ઞાનાલય',description:'ગુરુશાળાનું વાર્તા, અભ્યાસ અને જીવંત સ્મૃતિ માટેનું જ્ઞાનસ્થાન.',eyebrow:'ગુરુશાળા જ્ઞાનાલય',hero:'વાર્તા વાંચો. વિચાર પરખો. જીવનમાં ઉતારો.',lead:'અહીં વાર્તા, ચિત્ર, પરંપરા અને આજના જીવનના પ્રશ્નો એક સાથે શીખવાના સાધન બને છે.',issueLabel:'માતૃવર્તુળ • અંક 01 • 12 પાનાંનું કલર વિઝ્યુઅલ પ્રૂફ',issueTitle:'માતૃવર્તુળ: માતાઓની વાપસી',issueText:'મીરા ડિજિટલ અવાજ અને તુલનાના દબાણથી શરૂ કરે છે. બાની રોજિંદી સમજ તેને જૂના ફોલિયો સુધી લઈ જાય છે, જ્યાં માતૃવર્તુળની ગુણવત્તાઓ ધીમે ધીમે રોજિંદા અભ્યાસ, સીમા, સત્ય, કાળજી અને સમુદાયમાં જીવંત બને છે.',readIssue:'અંક 01 વાંચો',journeyTitle:'આ અંકની યાત્રા',j1:'નોટિફિકેશનનો અવાજ',j2:'બા અને રોજિંદી સમજ',j3:'માતૃવર્તુળ અને આઠ માતાઓ',j4:'નવ રાતોની અંદરની યાત્રા',j5:'વાર્તાથી નાની દૈનિક ક્રિયામાં',j6:'નાનો વર્તુળ અને માતાઓની વાપસી',nextLabel:'આગળની ઝલક',nextTitle:'The City of Raktabija',nextText:'પાનું 12 શહેરને અફવા, ગુસ્સો, વિભાજન અને વારંવાર ફેલાતી અસત્ય માહિતીના રૂપક તરીકે રજૂ કરીને આગળના અંકનો દરવાજો ખોલે છે.',proofNote:'હાલ ઉપલબ્ધ સામગ્રી 12 પાનાંનું કલર વિઝ્યુઅલ પ્રૂફ છે. તેને અંતિમ પ્રકાશિત આવૃત્તિ તરીકે રજૂ કરવામાં આવતું નથી.'},
    en:{title:'Gurushala Library',description:'Gurushala’s home for stories, study and living memory.',eyebrow:'Gurushala Library',hero:'Read the story. Examine the idea. Carry it into life.',lead:'Stories, images, inherited memory and present-day questions meet here as learning tools.',issueLabel:'Matrivartul • Issue 01 • 12-page colour visual proof',issueTitle:'Matrivartul: The Mothers Return',issueText:'Mira begins inside digital noise and comparison. Ba’s everyday wisdom leads her to an old folio, where the Matrivartul gradually becomes a set of lived qualities expressed through practice, boundaries, truth, care and community.',readIssue:'Read Issue 01',journeyTitle:'Journey through this issue',j1:'The notification storm',j2:'Ba and breakfast wisdom',j3:'The Matrivartul and Eight Mothers',j4:'Nine nights within',j5:'From story to daily practice',j6:'The small circle and the Mothers’ return',nextLabel:'Next issue teaser',nextTitle:'The City of Raktabija',nextText:'Page 12 opens the next chapter through a city shaped by rumours, outrage, division and multiplying unverified voices.',proofNote:'The material currently available is a 12-page colour visual proof. It is not being presented here as a final published edition.'},
    hi:{title:'गुरुशाला ज्ञानालय',description:'कहानियों, अध्ययन और जीवित स्मृति के लिए गुरुशाला का ज्ञान-स्थान।',eyebrow:'गुरुशाला ज्ञानालय',hero:'कहानी पढ़ें। विचार परखें। जीवन में उतारें।',lead:'यहाँ कहानी, चित्र, विरासत की स्मृति और आज के प्रश्न सीखने के साधन बनते हैं।',issueLabel:'मातृवर्तुल • अंक 01 • 12-पृष्ठ रंगीन दृश्य प्रूफ',issueTitle:'मातृवर्तुल: माताओं की वापसी',issueText:'मीरा डिजिटल शोर और तुलना के बीच से शुरू करती है। बा की रोज़मर्रा की समझ उसे एक पुराने फोलियो तक ले जाती है, जहाँ मातृवर्तुल धीरे-धीरे अभ्यास, सीमाओं, सत्य, देखभाल और समुदाय में जी जाने वाली शक्तियों में बदलता है।',readIssue:'अंक 01 पढ़ें',journeyTitle:'इस अंक की यात्रा',j1:'नोटिफिकेशन का तूफ़ान',j2:'बा और सुबह की समझ',j3:'मातृवर्तुल और आठ माताएँ',j4:'भीतर की नौ रातें',j5:'कहानी से रोज़मर्रा के अभ्यास तक',j6:'छोटा वृत्त और माताओं की वापसी',nextLabel:'अगले अंक की झलक',nextTitle:'The City of Raktabija',nextText:'पृष्ठ 12 अफ़वाह, आक्रोश, विभाजन और बढ़ती अपुष्ट आवाज़ों से बने शहर के रूपक के साथ अगले अध्याय का द्वार खोलता है।',proofNote:'अभी उपलब्ध सामग्री 12-पृष्ठ का रंगीन दृश्य प्रूफ है। इसे अंतिम प्रकाशित संस्करण के रूप में प्रस्तुत नहीं किया जा रहा है।'}
  },
  matrivartul:{
    gu:{title:'માતૃવર્તુળ અંક 01 | ગુરુશાળા',description:'માતૃવર્તુળ અંક 01 નું 12 પાનાંનું કલર વિઝ્યુઅલ પ્રૂફ.',eyebrow:'માતૃવર્તુળ • અંક 01',hero:'The Mothers Return',lead:'આ 12 પાનાંનો દૃશ્ય પ્રૂફ મીરાની યાત્રાને ડિજિટલ અવાજથી અંદરની શાંતિ, જીવંત ગુણો અને નાનાં સમુદાય સુધી અનુસરે છે.',visualNote:'કોમિકના મૂળ પાનાં મુખ્યત્વે અંગ્રેજીમાં છે. આ વેબ રીડરનો સંદર્ભ અને નેવિગેશન ગુજરાતી, અંગ્રેજી અને હિન્દીમાં બદલી શકાય છે.',mapTitle:'વાર્તાનો નકશો',m1:'પાનાં 1–2: અવાજ અને બાની સમજ',m2:'પાનું 3: જૂનો ફોલિયો અને માતૃવર્તુળ',m3:'પાનાં 4 અને 7: આઠ માતાઓને જીવવાના ગુણ તરીકે જોવું',m4:'પાનાં 5–6 અને 9: શ્વાસ, સીમા, પ્રતિભાવ અને દૈનિક અભ્યાસ',m5:'પાનું 8: Nine Nights Within',m6:'પાનાં 10–11: નાનો વર્તુળ અને સાથે જીવાતી સમજ',m7:'પાનું 12: The City of Raktabija ની ઝલક',readerTitle:'સંપૂર્ણ 12 પાનાં વાંચો',readerText:'કોઈ પણ પાનું મોટું જોવા માટે તેના પર ક્લિક કરો. તીર કીથી આગળ-પાછળ જઈ શકાય છે.',backLibrary:'જ્ઞાનાલય પર પાછા જાઓ',nextLabel:'આગળ શું?',nextTitle:'The City of Raktabija',nextText:'અંતિમ પાનું આગળના અંકને ડિજિટલ અફવા, વધતો ગુસ્સો અને ગુણાકાર થતી અસત્ય અવાજોની દુનિયા તરીકે રજૂ કરે છે.',p1:'પાનું 1 • The Notification Storm',p2:'પાનું 2 • Breakfast Wisdom',p3:'પાનું 3 • The Folio',p4:'પાનું 4 • The Ashta Matrika',p5:'પાનું 5 • The First Practice',p6:'પાનું 6 • The Age of Noise',p7:'પાનું 7 • The Eight Mothers',p8:'પાનું 8 • Nine Nights Within',p9:'પાનું 9 • From Story to Practice',p10:'પાનું 10 • The Small Circle',p11:'પાનું 11 • The Mothers Return',p12:'પાનું 12 • The City of Raktabija'},
    en:{title:'Matrivartul Issue 01 | Gurushala',description:'The 12-page colour visual proof of Gurushala Matrivartul Issue 01.',eyebrow:'Matrivartul • Issue 01',hero:'The Mothers Return',lead:'This 12-page visual proof follows Mira from digital noise toward inner practice, lived qualities and a small circle of community.',visualNote:'The original comic pages are primarily in English. The reader interface and context can be switched between Gujarati, English and Hindi.',mapTitle:'Story map',m1:'Pages 1–2: noise and Ba’s everyday wisdom',m2:'Page 3: the old folio and the Matrivartul',m3:'Pages 4 and 7: the Eight Mothers as qualities to live',m4:'Pages 5–6 and 9: breath, boundaries, response and daily practice',m5:'Page 8: Nine Nights Within',m6:'Pages 10–11: the small circle and wisdom lived together',m7:'Page 12: a teaser for The City of Raktabija',readerTitle:'Read all 12 pages',readerText:'Select any page to enlarge it. Use the arrow keys to move through the reader.',backLibrary:'Back to Library',nextLabel:'What comes next?',nextTitle:'The City of Raktabija',nextText:'The final page points toward a new story-world of digital rumours, multiplying outrage and unverified voices.',p1:'Page 1 • The Notification Storm',p2:'Page 2 • Breakfast Wisdom',p3:'Page 3 • The Folio',p4:'Page 4 • The Ashta Matrika',p5:'Page 5 • The First Practice',p6:'Page 6 • The Age of Noise',p7:'Page 7 • The Eight Mothers',p8:'Page 8 • Nine Nights Within',p9:'Page 9 • From Story to Practice',p10:'Page 10 • The Small Circle',p11:'Page 11 • The Mothers Return',p12:'Page 12 • The City of Raktabija'},
    hi:{title:'मातृवर्तुल अंक 01 | गुरुशाला',description:'गुरुशाला मातृवर्तुल अंक 01 का 12-पृष्ठ रंगीन दृश्य प्रूफ।',eyebrow:'मातृवर्तुल • अंक 01',hero:'The Mothers Return',lead:'यह 12-पृष्ठ दृश्य प्रूफ मीरा की यात्रा को डिजिटल शोर से भीतर के अभ्यास, जीए जाने वाले गुणों और छोटे समुदाय तक ले जाता है।',visualNote:'मूल कॉमिक पृष्ठ मुख्यतः अंग्रेज़ी में हैं। रीडर का संदर्भ और नेविगेशन गुजराती, अंग्रेज़ी और हिंदी में बदला जा सकता है।',mapTitle:'कहानी का नक्शा',m1:'पृष्ठ 1–2: शोर और बा की रोज़मर्रा की समझ',m2:'पृष्ठ 3: पुराना फोलियो और मातृवर्तुल',m3:'पृष्ठ 4 और 7: आठ माताएँ जीए जाने वाले गुणों के रूप में',m4:'पृष्ठ 5–6 और 9: श्वास, सीमाएँ, प्रतिक्रिया और दैनिक अभ्यास',m5:'पृष्ठ 8: Nine Nights Within',m6:'पृष्ठ 10–11: छोटा वृत्त और साथ जी जाने वाली समझ',m7:'पृष्ठ 12: The City of Raktabija की झलक',readerTitle:'सभी 12 पृष्ठ पढ़ें',readerText:'किसी भी पृष्ठ को बड़ा देखने के लिए चुनें। तीर कुंजियों से आगे-पीछे जा सकते हैं।',backLibrary:'ज्ञानालय पर वापस जाएँ',nextLabel:'आगे क्या?',nextTitle:'The City of Raktabija',nextText:'अंतिम पृष्ठ डिजिटल अफ़वाहों, बढ़ते आक्रोश और अपुष्ट आवाज़ों की नई कहानी-दुनिया की ओर संकेत करता है।',p1:'पृष्ठ 1 • The Notification Storm',p2:'पृष्ठ 2 • Breakfast Wisdom',p3:'पृष्ठ 3 • The Folio',p4:'पृष्ठ 4 • The Ashta Matrika',p5:'पृष्ठ 5 • The First Practice',p6:'पृष्ठ 6 • The Age of Noise',p7:'पृष्ठ 7 • The Eight Mothers',p8:'पृष्ठ 8 • Nine Nights Within',p9:'पृष्ठ 9 • From Story to Practice',p10:'पृष्ठ 10 • The Small Circle',p11:'पृष्ठ 11 • The Mothers Return',p12:'पृष्ठ 12 • The City of Raktabija'}
  }
};
function readLanguage(){try{const x=localStorage.getItem('gurushala-language');return ['gu','en','hi'].includes(x)?x:'gu'}catch(e){return 'gu'}}
function saveLanguage(lang){try{localStorage.setItem('gurushala-language',lang)}catch(e){}}
function applyLibraryLanguage(lang,persist=false){
  const page=document.body.dataset.page;const copy={...libraryShared[lang],...(libraryPages[page]?.[lang]||{})};
  document.documentElement.lang=lang;document.title=copy.title||document.title;
  const meta=document.getElementById('metaDescription');if(meta&&copy.description)meta.setAttribute('content',copy.description);
  document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(copy[k]!==undefined)el.textContent=copy[k]});
  document.querySelectorAll('.langs').forEach(el=>el.setAttribute('aria-label',copy.languageLabel));
  document.querySelectorAll('[data-lang]').forEach(btn=>{const active=btn.dataset.lang===lang;btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',String(active))});
  if(persist)saveLanguage(lang);
}
document.querySelectorAll('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>applyLibraryLanguage(btn.dataset.lang,true)));
applyLibraryLanguage(readLanguage());
