const shared={
  gu:{home:'મુખ્ય પાનું',projects:'પ્રકલ્પો',pilot:'ડિજિટલ સાથી',transparency:'પારદર્શિતા',join:'જોડાઓ',languageLabel:'ભાષા પસંદ કરો',footer:'અનુસૂચિત જાતિની મહિલાઓની માલિકી, નેતૃત્વ અને સંચાલન હેઠળની શિક્ષણ અને સાંસ્કૃતિક પહેલ, જે દરેકને સન્માનથી આવકારે છે.',principles:'શીખણ • સર્જનાત્મકતા • ગૌરવ • પ્રકૃતિ • સમુદાય'},
  en:{home:'Home',projects:'Projects',pilot:'Digital Saheli',transparency:'Transparency',join:'Join',languageLabel:'Choose language',footer:'An education and cultural initiative owned, led and run by Scheduled Caste women, welcoming everyone with dignity.',principles:'Learning • Creativity • Dignity • Nature • Community'},
  hi:{home:'मुख्य पृष्ठ',projects:'परियोजनाएँ',pilot:'डिजिटल सहेली',transparency:'पारदर्शिता',join:'जुड़ें',languageLabel:'भाषा चुनें',footer:'अनुसूचित जाति की महिलाओं के स्वामित्व, नेतृत्व और संचालन वाली शिक्षा और सांस्कृतिक पहल, जो सभी का सम्मान के साथ स्वागत करती है।',principles:'शिक्षा • रचनात्मकता • गरिमा • प्रकृति • समुदाय'}
};
const pages={
  projects:{
    gu:{title:'પ્રકલ્પો | ગુરુશાળા',description:'ગુરુશાળાના હાલના અને આયોજન હેઠળના પ્રકલ્પો.',eyebrow:'ગુરુશાળા પ્રકલ્પો',hero:'નાની શરૂઆત. સ્પષ્ટ સ્થિતિ. લાંબી દૃષ્ટિ.',lead:'દરેક પ્રકલ્પમાં હેતુ, હાલની સ્થિતિ અને આગળનું પગલું સ્પષ્ટ રીતે દર્શાવવામાં આવે છે.',digitalStatus:'તૈયારીમાં',digitalTitle:'ડિજિટલ સાથી પાયલોટ',digitalText:'10–15 મહિલાઓ માટે સ્માર્ટફોન આત્મવિશ્વાસ, ઑનલાઇન સલામતી, ડિજિટલ ચુકવણી અને ઉપયોગી AI અંગેનું ગુજરાતી પ્રાયોગિક સત્ર.',digitalCta:'પાયલોટ યોજના જુઓ',libraryStatus:'રચનામાં',libraryTitle:'ગુરુશાળા જ્ઞાનાલય',libraryText:'પુસ્તકો, સંશોધન, સામયિકો, વાર્તાઓ અને વ્યવહારુ માર્ગદર્શિકાઓ માટેનું વધતું જ્ઞાનસ્થાન.',livelihoodStatus:'આયોજિત',livelihoodTitle:'મહિલા જીવનોપાર્જન સ્ટુડિયો',livelihoodText:'હસ્તકલા, ડિજિટલ સેવા, ઉત્પાદન વિકાસ અને સ્થાનિક ઉદ્યોગ માટેનો ભાવિ માર્ગ.',centreStatus:'આયોજિત',centreTitle:'સીડિંગ સેન્ટર',centreText:'શીખણ, સર્જન, મળાપ, પ્રકૃતિ અને સમુદાય કાર્ય માટેનું ભૌતિક સ્થાન.',ruleTitle:'સ્થિતિનો નિયમ',ruleText:'વિચારને વિચાર, આયોજનને આયોજન અને પૂર્ણ થયેલા કાર્યને જ પુરાવા સાથે પ્રગતિ કહેવાશે.'},
    en:{title:'Projects | Gurushala',description:'Current and planned Gurushala projects.',eyebrow:'Gurushala projects',hero:'Small beginnings. Clear status. Long horizon.',lead:'Every project shows its purpose, present stage and next step without turning plans into achievements.',digitalStatus:'Preparing',digitalTitle:'Digital Saheli Pilot',digitalText:'A practical Gujarati session for 10–15 women covering smartphone confidence, online safety, digital payments and useful AI.',digitalCta:'View pilot plan',libraryStatus:'Building',libraryTitle:'Gurushala Library',libraryText:'A growing home for books, research, magazines, stories and practical learning guides.',livelihoodStatus:'Planned',livelihoodTitle:'Women’s Livelihood Studio',livelihoodText:'A future pathway for craft, digital services, product development and local enterprise.',centreStatus:'Planned',centreTitle:'Seeding Centre',centreText:'A physical place for learning, making, gathering, nature and community work.',ruleTitle:'Status rule',ruleText:'Ideas are called ideas, plans are called plans, and only completed work is presented as evidence of progress.'},
    hi:{title:'परियोजनाएँ | गुरुशाला',description:'गुरुशाला की वर्तमान और नियोजित परियोजनाएँ।',eyebrow:'गुरुशाला परियोजनाएँ',hero:'छोटी शुरुआत। स्पष्ट स्थिति। लंबी दृष्टि।',lead:'हर परियोजना में उद्देश्य, वर्तमान चरण और अगला कदम स्पष्ट रूप से दिखाया जाता है।',digitalStatus:'तैयारी में',digitalTitle:'डिजिटल सहेली पायलट',digitalText:'10–15 महिलाओं के लिए स्मार्टफोन आत्मविश्वास, ऑनलाइन सुरक्षा, डिजिटल भुगतान और उपयोगी AI पर व्यावहारिक गुजराती सत्र।',digitalCta:'पायलट योजना देखें',libraryStatus:'निर्माणाधीन',libraryTitle:'गुरुशाला ज्ञानालय',libraryText:'पुस्तकों, शोध, पत्रिकाओं, कहानियों और व्यावहारिक मार्गदर्शिकाओं का बढ़ता ज्ञान-स्थान।',livelihoodStatus:'नियोजित',livelihoodTitle:'महिला आजीविका स्टूडियो',livelihoodText:'शिल्प, डिजिटल सेवाओं, उत्पाद विकास और स्थानीय उद्यम के लिए भावी मार्ग।',centreStatus:'नियोजित',centreTitle:'सीडिंग सेंटर',centreText:'शिक्षा, सृजन, मिलन, प्रकृति और सामुदायिक कार्य के लिए भौतिक स्थान।',ruleTitle:'स्थिति का नियम',ruleText:'विचार को विचार, योजना को योजना और केवल पूर्ण कार्य को प्रगति का प्रमाण कहा जाएगा।'}
  },
  pilot:{
    gu:{title:'ડિજિટલ સાથી | ગુરુશાળા',description:'મહિલાઓ માટેનો પ્રસ્તાવિત ડિજિટલ આત્મવિશ્વાસ પાયલોટ.',status:'તૈયારીમાં',hero:'ડિજિટલ સાથી: આત્મવિશ્વાસથી ડિજિટલ દુનિયામાં પ્રવેશ.',lead:'10–15 પુખ્ત મહિલાઓ માટે ત્રણ કલાકનું ગુજરાતી પ્રાયોગિક શીખણ સત્ર. ભાગ લેનાર પોતાની જ ફોન પર સલામતી, ચુકવણી અને ઉપયોગી AI શીખશે.',group:'લક્ષિત જૂથ',groupText:'12 મહિલાઓ, મહત્તમ 15 ભાગ લેનાર.',format:'સમય',formatText:'એક દિવસમાં ત્રણ કલાકનું પ્રાયોગિક સત્ર.',topics:'મુખ્ય વિષયો',topicsText:'સ્માર્ટફોન, સલામતી, ડિજિટલ ચુકવણી અને ઉપયોગી AI.',journey:'શીખણ યાત્રા',s1:'સ્વાગત અને સંમતિ',s1t:'પરિચય, ગોપનીયતા અને ટૂંકી આત્મવિશ્વાસ ચકાસણી.',s2:'ફોન આત્મવિશ્વાસ',s2t:'સેટિંગ, લખાણનું કદ, બ્રાઇટનેસ અને મૂળભૂત નેવિગેશન.',s3:'ઑનલાઇન સલામતી',s3t:'WhatsApp ગોપનીયતા, શંકાસ્પદ લિંક્સ, OTP અને PIN સુરક્ષા.',s4:'ડિજિટલ ચુકવણી',s4t:'ચુકવણી પહેલાં નામ અને રકમ ચકાસવી, સ્કેમ ઓળખવી અને રસીદ સાચવવી.',s5:'ઉપયોગી AI',s5t:'એક વ્યવહારુ પ્રશ્ન પૂછવો, જવાબ તપાસવો અને વ્યક્તિગત માહિતી ન આપવી.',s6:'અંતિમ કાર્ય અને પ્રતિસાદ',s6t:'નાનું પ્રાયોગિક કાર્ય, પ્રતિસાદ અને આગળની જરૂરિયાત નોંધવી.',needs:'હાલમાં શું જોઈએ',n1:'ગામ અને સ્થળની પુષ્ટિ',n2:'મુખ્ય ટ્રેનરની નિમણૂક',n3:'બે મહિલા સ્વયંસેવકો',n4:'ગુજરાતી શીખણ પત્રકો અને સંમતિ ફોર્મ',n5:'તારીખ અને ભાગ લેનાર યાદી',safety:'આ પાયલોટ પુખ્ત મહિલાઓ માટે છે. બાળકો સાથેની પ્રવૃત્તિઓ સુરક્ષા અને સંમતિ નીતિઓ મંજૂર થયા પછી જ શરૂ થવી જોઈએ.',back:'બધા પ્રકલ્પો જુઓ'},
    en:{title:'Digital Saheli | Gurushala',description:'A proposed digital-confidence pilot for adult women.',status:'Preparing',hero:'Digital Saheli: entering the digital world with confidence.',lead:'A three-hour Gujarati practical learning session for 10–15 adult women. Participants learn on their own phones, focusing on safety, payments and useful AI.',group:'Target group',groupText:'12 women, with a maximum of 15 participants.',format:'Duration',formatText:'One practical three-hour session held in a single day.',topics:'Core topics',topicsText:'Smartphones, online safety, digital payments and useful AI.',journey:'Learning journey',s1:'Welcome and consent',s1t:'Introductions, privacy and a short confidence check.',s2:'Phone confidence',s2t:'Settings, text size, brightness and basic navigation.',s3:'Online safety',s3t:'WhatsApp privacy, suspicious links, OTP and PIN protection.',s4:'Digital payments',s4t:'Check names and amounts before paying, recognise scams and keep receipts.',s5:'Useful AI',s5t:'Ask one practical question, check the answer and avoid sharing personal information.',s6:'Final task and feedback',s6t:'A small practical task, participant feedback and next learning needs.',needs:'What is still needed',n1:'Confirm village and venue',n2:'Appoint the lead trainer',n3:'Recruit two women volunteers',n4:'Prepare Gujarati learning sheets and consent forms',n5:'Confirm the date and participant list',safety:'This pilot is for adult women. Activities involving children should begin only after safeguarding and consent policies are approved.',back:'View all projects'},
    hi:{title:'डिजिटल सहेली | गुरुशाला',description:'वयस्क महिलाओं के लिए प्रस्तावित डिजिटल आत्मविश्वास पायलट।',status:'तैयारी में',hero:'डिजिटल सहेली: आत्मविश्वास के साथ डिजिटल दुनिया में प्रवेश।',lead:'10–15 वयस्क महिलाओं के लिए तीन घंटे का व्यावहारिक गुजराती सत्र। प्रतिभागी अपने फोन पर सुरक्षा, भुगतान और उपयोगी AI सीखेंगी।',group:'लक्षित समूह',groupText:'12 महिलाएँ, अधिकतम 15 प्रतिभागी।',format:'समय',formatText:'एक दिन में आयोजित तीन घंटे का व्यावहारिक सत्र।',topics:'मुख्य विषय',topicsText:'स्मार्टफोन, ऑनलाइन सुरक्षा, डिजिटल भुगतान और उपयोगी AI।',journey:'सीखने की यात्रा',s1:'स्वागत और सहमति',s1t:'परिचय, गोपनीयता और छोटी आत्मविश्वास जाँच।',s2:'फोन आत्मविश्वास',s2t:'सेटिंग, टेक्स्ट आकार, ब्राइटनेस और मूल नेविगेशन।',s3:'ऑनलाइन सुरक्षा',s3t:'WhatsApp गोपनीयता, संदिग्ध लिंक, OTP और PIN सुरक्षा।',s4:'डिजिटल भुगतान',s4t:'भुगतान से पहले नाम और राशि जाँचना, धोखाधड़ी पहचानना और रसीद रखना।',s5:'उपयोगी AI',s5t:'एक व्यावहारिक प्रश्न पूछना, उत्तर जाँचना और निजी जानकारी साझा न करना।',s6:'अंतिम कार्य और प्रतिक्रिया',s6t:'छोटा व्यावहारिक कार्य, प्रतिक्रिया और आगे की सीखने की जरूरतें।',needs:'अभी क्या आवश्यक है',n1:'गाँव और स्थल की पुष्टि',n2:'मुख्य प्रशिक्षक नियुक्त करना',n3:'दो महिला स्वयंसेवकों की भर्ती',n4:'गुजराती सीखने की सामग्री और सहमति फॉर्म तैयार करना',n5:'तारीख और प्रतिभागी सूची की पुष्टि',safety:'यह पायलट वयस्क महिलाओं के लिए है। बच्चों से जुड़ी गतिविधियाँ सुरक्षा और सहमति नीतियाँ स्वीकृत होने के बाद ही शुरू होनी चाहिए।',back:'सभी परियोजनाएँ देखें'}
  }
};
function safeGet(k){try{return localStorage.getItem(k)}catch(e){return null}}function safeSet(k,v){try{localStorage.setItem(k,v);localStorage.setItem('gurushala-language-chosen','1')}catch(e){}}
function applyPageLanguage(lang,persist=false){const page=document.body.dataset.page;const t=pages[page][lang]||pages[page].gu,s=shared[lang]||shared.gu;document.documentElement.lang=lang;document.title=t.title;document.getElementById('metaDescription').content=t.description;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(k in t)el.textContent=t[k];else if(k in s)el.textContent=s[k]});document.querySelectorAll('[data-lang]').forEach(b=>{const a=b.dataset.lang===lang;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))});document.querySelectorAll('.langs').forEach(el=>el.setAttribute('aria-label',s.languageLabel));if(persist)safeSet('gurushala-language',lang)}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>applyPageLanguage(b.dataset.lang,true)));const chosen=safeGet('gurushala-language-chosen')==='1',stored=chosen?safeGet('gurushala-language'):null;applyPageLanguage(stored&&shared[stored]?stored:'gu');
